export type ProjectScreenshot = {
  src: string;
  alt: string;
};

export type SecurityProject = {
  id: string;
  number: string;
  title: string;
  category: string;
  description: string;
  features: string[];
  technology: string;
  githubUrl: string;
  demoUrl: string;
  screenshots: ProjectScreenshot[];
};

export const projects: SecurityProject[] = [
  {
    id: "log-analyzer",
    number: "01",
    title: "Log Analyzer & Threat Detector",
    category: "Defensive Security",
    description:
      "A Python-based tool that analyses Apache-style server logs and identifies suspicious activities such as repeated failed login attempts, access to sensitive administrative paths and potentially malicious IP behaviour.",
    features: [
      "Parses Apache-style log files",
      "Counts successful and failed requests",
      "Detects repeated failed login attempts",
      "Detects access to administrative paths",
      "Identifies suspicious IP addresses",
      "Produces a readable threat report",
      "Uses risk-based detection logic"
    ],
    technology: "Python",
    githubUrl:
      "https://github.com/iam-varun2008/Log-Analyzer-and-Threat-Detector",
    demoUrl: "/projects/log-analyzer-demo.mp4",
    screenshots: [
      {
        src: "/projects/log-analyzer-structure.webp",
        alt: "Project structure for the Log Analyzer and Threat Detector"
      },
      {
        src: "/projects/log-analyzer-terminal.webp",
        alt: "Log Analyzer running in a terminal with an Apache-style log file"
      },
      {
        src: "/projects/log-analyzer-results.webp",
        alt: "Suspicious activity results produced by the Log Analyzer"
      },
      {
        src: "/projects/log-analyzer-report.webp",
        alt: "Readable threat report generated by the Log Analyzer"
      }
    ]
  },
  {
    id: "port-scanner",
    number: "02",
    title: "Network Port Scanner & Vulnerability Risk Reporter",
    category: "Offensive Security / Network Security",
    description:
      "A Python-based network security tool that scans selected TCP ports, identifies open services, attempts basic banner detection and produces risk levels and security recommendations.",
    features: [
      "Scans commonly used TCP ports",
      "Detects open ports",
      "Attempts service banner collection",
      "Assigns severity levels",
      "Explains security risks",
      "Provides recommendations",
      "Generates a text report",
      "Includes an ethical-use notice"
    ],
    technology: "Python, TCP sockets and networking concepts",
    githubUrl:
      "https://github.com/iam-varun2008/port-vulnerability-scanner",
    demoUrl: "/projects/port-scanner-demo.mp4",
    screenshots: [
      {
        src: "/projects/port-scanner-structure.webp",
        alt: "Project structure for the Network Port Scanner"
      },
      {
        src: "/projects/port-scanner-terminal.webp",
        alt: "Authorized localhost scan running in the terminal"
      },
      {
        src: "/projects/port-scanner-results.webp",
        alt: "Open ports and risk levels identified by the Network Port Scanner"
      },
      {
        src: "/projects/port-scanner-report.webp",
        alt: "Security recommendations in the generated port scan report"
      }
    ]
  }
];
